### ISSUE TITLE
User routes not working

### ISSUE THREAD

**Issue by heyjones** [zype/zype-wordpress-plugin#20]
I defined my User routes under Settings > Users, but when I attempt to access them I get a 404 and this warning is coming up on every page of the site:

`Warning: trim() expects parameter 1 to be string, array given in /wordpress/wp-content/plugins/zype-wordpress-plugin/vendor/illuminate/routing/Router.php on line 472`

**Comment by whoughton** [comment]
We've also seen this issue and have identified it, we're currently in the process of developing the fix for it. If you need an intermediary fix, please set $auth_url to false here:
https://github.com/zype/zype-wordpress-plugin/blob/master/resources/routes.php#L11

**Comment by whoughton** [comment]
This should have been fixed a while ago, sorry for the delay in closing this.
