### ISSUE TITLE
Error Upon Plugin Activation

### ISSUE THREAD

**Issue by nboaldin** [zype/zype-wordpress-plugin#45]
**WP Version: 4.9.8
PHP Version: 7.0
Framework: Genesis 2.6.1
Child Theme: ACF 5.7.3**

Fatal error: Uncaught Error: Class 'Themosis\Foundation\Application' not found in /home/megaphonedemo/public_html/prepsports/wp-content/plugins/zype-wordpress-plugin-master/core.php:143 Stack trace: #0 /home/megaphonedemo/public_html/prepsports/wp-content/plugins/zype-wordpress-plugin-master/core.php(86): Themosis->bootstrap() #1 /home/megaphonedemo/public_html/prepsports/wp-content/plugins/zype-wordpress-plugin-master/core.php(97): Themosis->__construct() #2 /home/megaphonedemo/public_html/prepsports/wp-content/plugins/zype-wordpress-plugin-master/core.php(337): Themosis::instance() #3 /home/megaphonedemo/public_html/prepsports/wp-content/plugins/zype-wordpress-plugin-master/zype.php(4): require_once('/home/megaphone...') #4 /home/megaphonedemo/public_html/prepsports/wp-admin/includes/plugin.php(1897): include('/home/megaphone...') #5 /home/megaphonedemo/public_html/prepsports/wp-admin/plugins.php(178): plugin_sandbox_scrape('zype-wordpress-...') #6 {main} thrown in /home/megaphonedemo/public_html/prepsports/wp-content/plugins/zype-wordpress-plugin-master/core.php on line 143

**Comment by MatayoshiMariano** [comment]
Hey @nboaldin,

Did you run `composer install`?

**Comment by nboaldin** [comment]
Ahhh. I get the version with the dependencies on Google Drive correct?

**Comment by nboaldin** [comment]
I see. I did not install dependencies. Thanks and sorry for the trouble.

**Comment by MatayoshiMariano** [comment]
@nboaldin Awesome, no problem!
